# -*- mode: ruby -*-
# # vi: set ft=ruby :
# Vagrantfile to create multiple generic virtual machines based on a yaml dictionary.
#
#    From: http://blog.scottlowe.org/2014/10/22/multi-machine-vagrant-with-yaml/
#    Modfified By: Karl Vietmeier
#
# Requires "servers.yml" to be in local directory
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
 
# Require YAML module
require 'yaml'
 
# Read YAML file with box details
servers = YAML.load_file('servers.yml')

ssh_user = "vagrant"
ssh_pass = "vagrant"

# Create Virtual Machines
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Default is 2200..something, but port 2200 is used by some tools
  config.vm.usable_port_range = 2800..2900
 
  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.ssh.username = servers["ssh_user"]
      srv.ssh.password = servers["ssh_pass"]
      srv.vm.hostname = servers["name"]
      srv.vm.network "private_network", ip: servers["ip1"]
      srv.vm.network "private_network", ip: servers["ip2"]
      #srv.vm.network "private_network", ip: servers["ip3"]  
      
      # Fix for no tty with Ubuntu - need if statement because this breaks with centos
      # added "os" dictionary entry in yaml.
      if servers["os"] == "ubuntu"
        config.vm.provision "fix-no-tty", type: "shell" do |s|
          s.privileged = false
          s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
        end
      end
      
      # Copy in my public key
      config.vm.provision "Copy my keys", type: "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          #echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
      
      # VM parameters
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
        vb.cpus = servers["cpus"]
      end
      
      # Copy over local /etc/hosts
      #config.vm.provision "file", source: "/etc/hosts", destination: "/etc/hosts"
    end
  end
end



